spring.application.name=uc-migration-regression-test-suite-sample
server.port=8082

#added for accurator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when-authorized
management.info.env.enabled=true

info.app.name=UC Migration Regression Test Suite Sample
info.app.description=Assembly to COBOL XML regression testing framework
info.app.version=0.1.0

#authentication
regression.authentication.url=http://localhost:8081/authentication/token
regression.authentication.username=test
regression.authentication.password=test123

#soap client
regression.soap.url=http://localhost:8081/soap
regression.soap.assembly.namespace=http://sample.uc.se/migration/assembly
regression.soap.cobol.namespace=http://sample.uc.se/migration/cobol
